version: '3'
services:
  api:
    image: node:12
    container_name: antonpi-api
    command: node_modules/.bin/nodemon -- -r esm -r dotenv/config src/app.js
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - "5001:5001"
    depends_on:
      - redis
  redis:
    image: redis
    container_name: antonpi-redis
