version: '3'
services:
  api:
    container_name: antonpi-core
    build:
      context: ..
      dockerfile: docker/Dockerfile.prod
    env_file: ../.env
    ports:
      - "8002:5001"
    depends_on:
      - redis
    restart: unless-stopped
  redis:
    image: redis
    container_name: antonpi-redis
